import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('button', { name: 'Resume' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').press('ControlOrMeta+a');
  await page.locator('input[type="text"]').fill('Playwright test');
  await page.getByRole('checkbox', { name: 'testMultiFileAndRepos' }).uncheck();
  await page.getByRole('button', { name: 'Create Report' }).click();
  await page.getByRole('button', { name: '+ Add Education' }).click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('UBCO');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('Kelowna');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('CS');
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).fill('September 2023 - May 2027');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: '+ Add Award' }).click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('Deans list');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('UBCO');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('2023-2027');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: '+ Add Experience' }).click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('Developer');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('UBCO');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('Kelowna');
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).fill('September 2025 - May 2026');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('li:nth-child(5) > button').first().click();
  await page.getByRole('button', { name: '+ Add', exact: true }).click();
  await page.locator('div:nth-child(5) > input').click();
  await page.locator('div:nth-child(5) > input').fill('Testing playwright');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('div:nth-child(5) > div > span > span:nth-child(2) > button').click();
  await page.locator('span').filter({ hasText: 'Game-Jam-2025 | C#, MATLAB' }).getByRole('textbox').fill('C#, MATLAB, C');
  await page.locator('span').filter({ hasText: 'Game-Jam-2025 | C#, MATLAB' }).getByRole('textbox').press('Enter');
});